//! OpenAPI 3.x derived spec for `agsh serve`, generated by `utoipa` from the `#[utoipa::path]`
//! annotations on each handler. Served at `GET /v1/openapi.json` and rendered by Swagger UI at
//! `GET /v1/docs`.
//!
//! Keeping the spec inline in the binary (via derive macros rather than a hand-written JSON
//! file) means it can never drift from the implementation — wire-shape changes that forget the
//! annotation fail to compile or surface in the spec as missing fields.

use axum::Router;
use utoipa::{
    Modify, OpenApi,
    openapi::security::{Http, HttpAuthScheme, SecurityScheme},
};
use utoipa_swagger_ui::SwaggerUi;

use crate::server::{handlers, state::ServerState};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "agsh HTTP API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Service-to-service API for driving agsh agent turns programmatically. \
                       Mirrors the wire format described in the HTTP API docs.",
        license(name = "MIT")
    ),
    paths(
        handlers::sessions::create_session,
        handlers::sessions::list_sessions,
        handlers::sessions::get_session,
        handlers::sessions::patch_session,
        handlers::sessions::delete_session,
        handlers::messages::list_messages,
        handlers::turn::submit_turn,
        handlers::turn::cancel_turn,
        handlers::responses::respond,
        handlers::info::info,
        handlers::info::skills,
        handlers::info::mcp,
        handlers::discovery::live,
        handlers::discovery::ready,
    ),
    components(schemas(
        crate::server::errors::ProblemDetail,
        crate::server::handlers::sessions::CreateSessionRequest,
        crate::server::handlers::sessions::CapabilitiesBody,
        crate::server::http_frontend::SessionCapabilities,
        crate::server::handlers::sessions::SessionResponse,
        crate::server::handlers::sessions::ListSessionsResponse,
        crate::server::handlers::sessions::PatchSessionRequest,
        crate::server::handlers::turn::TurnRequest,
        crate::server::handlers::turn::TurnOptions,
        crate::server::handlers::turn::TurnResponse,
        crate::server::handlers::turn::ToolCallView,
        crate::server::handlers::turn::ToolCallContentView,
        crate::server::handlers::turn::UsageView,
        crate::server::handlers::turn::NoticeView,
        crate::server::handlers::responses::ResponseBody,
        crate::server::handlers::responses::PermissionDecision,
        crate::server::handlers::messages::MessagesResponse,
        crate::server::handlers::messages::MessageView,
        crate::server::handlers::messages::ContentBlockView,
        crate::server::handlers::messages::ToolResultContentView,
        crate::server::handlers::info::InfoResponse,
        crate::server::handlers::info::SkillView,
        crate::server::handlers::info::McpServerView,
        crate::server::handlers::discovery::LiveResponse,
        crate::server::handlers::discovery::ReadyResponse,
    )),
    modifiers(&SecurityAddon),
    tags(
        (name = "sessions", description = "Session CRUD"),
        (name = "turn", description = "Turn lifecycle (submit / re-attach / cancel / mid-turn responses)"),
        (name = "discovery", description = "Server info, installed skills, MCP server status"),
        (name = "health", description = "Liveness / readiness probes"),
    )
)]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi
            .components
            .get_or_insert_with(utoipa::openapi::Components::default);
        components.add_security_scheme(
            "bearerAuth",
            SecurityScheme::Http(
                Http::builder()
                    .scheme(HttpAuthScheme::Bearer)
                    .description(Some(
                        "Bearer token configured in [[serve.tokens]]. Scopes: sessions:r, \
                         sessions:w, skills:r, mcp:r.",
                    ))
                    .build(),
            ),
        );
    }
}

/// Wire the OpenAPI JSON endpoint and Swagger UI into the router. Both are public (no bearer
/// auth) so cross-language client tooling can hit them. `SwaggerUi` registers both
/// `/v1/docs/*` and `/v1/openapi.json` itself; no manual route definition is needed.
pub fn router() -> Router<ServerState> {
    Router::new().merge(SwaggerUi::new("/v1/docs").url("/v1/openapi.json", ApiDoc::openapi()))
}
