//! OpenAPI 3.x derived spec for `meka serve`, generated by `utoipa` from the `#[utoipa::path]`
//! annotations on each handler. Served at `GET /v1/openapi.json` and rendered by Swagger UI at
//! `GET /v1/docs`.
//!
//! Keeping the spec inline in the binary (via derive macros rather than a hand-written JSON file)
//! keeps most of it honest: a response type that changes shape changes the schema with it, because
//! the schema is derived from the type.
//!
//! It is not a guarantee, and has drifted. What the macros derive is the *shape*; what a handler
//! actually returns for a given input is prose in the annotation, and prose does not recompile. A
//! status code a handler stopped returning, or started returning, stays as written until someone
//! reads both. Treat an annotation as documentation with a compiler-checked type, not as a proof.

use axum::Router;
use utoipa::{
    Modify, OpenApi,
    openapi::security::{Http, HttpAuthScheme, SecurityScheme},
};
use utoipa_swagger_ui::SwaggerUi;

use crate::host::http::{handlers, state::ServerState};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "meka HTTP API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Service-to-service API for driving meka agent turns programmatically. \
                       Mirrors the wire format described in the HTTP API docs. A field that has \
                       no value is omitted from every response and event, never sent as `null`.",
        license(name = "MIT")
    ),
    paths(
        handlers::sessions::create_session,
        handlers::sessions::fork_session,
        handlers::sessions::list_sessions,
        handlers::sessions::get_session,
        handlers::sessions::patch_session,
        handlers::sessions::delete_session,
        handlers::messages::list_messages,
        handlers::messages::get_blob,
        handlers::turn::submit_turn,
        handlers::turn::cancel_turn,
        handlers::responses::respond,
        handlers::turn::stream_turn,
        handlers::conversation::compact,
        handlers::conversation::context,
        handlers::conversation::rewind,
        handlers::conversation::export,
        handlers::conversation::import,
        handlers::jobs::list_all,
        handlers::jobs::list_for_session,
        handlers::jobs::create,
        handlers::jobs::cancel,
        handlers::jobs::list_tasks,
        handlers::jobs::cancel_task,
        handlers::stores::get_skill,
        handlers::stores::put_skill,
        handlers::stores::delete_skill,
        handlers::stores::list_memories,
        handlers::stores::get_memory,
        handlers::stores::put_memory,
        handlers::stores::delete_memory,
        handlers::stores::list_tools,
        handlers::stores::instructions,
        handlers::stores::profiles,
        handlers::info::info,
        handlers::info::skills,
        handlers::info::mcp,
        handlers::info::mcp_tools,
        handlers::info::mcp_reconnect,
        handlers::discovery::live,
        handlers::discovery::ready,
    ),
    components(schemas(
        crate::host::http::errors::ProblemDetail,
        crate::host::http::handlers::sessions::CreateSessionRequest,
        crate::host::http::handlers::sessions::ForkSessionBody,
        crate::host::http::handlers::sessions::CapabilitiesBody,
        crate::host::http::http_frontend::SessionCapabilities,
        crate::host::http::http_frontend::PermissionRequiredEvent,
        crate::view::SessionView,
        crate::host::http::handlers::sessions::SessionResponse,
        crate::host::http::handlers::sessions::ListSessionsResponse,
        crate::host::http::handlers::sessions::PatchSessionRequest,
        crate::host::http::handlers::turn::TurnRequest,
        crate::host::http::handlers::turn::ImageInput,
        crate::host::http::handlers::turn::TurnOptions,
        crate::host::http::handlers::turn::TurnResponse,
        crate::host::http::handlers::turn::ToolCallView,
        crate::host::http::handlers::turn::ToolCallContentView,
        crate::host::http::handlers::turn::UsageView,
        crate::frontend::NoticeView,
        crate::host::http::handlers::responses::ResponseBody,
        crate::host::http::handlers::responses::PermissionDecision,
        crate::host::http::handlers::messages::MessagesResponse,
        crate::host::http::handlers::messages::MessageView,
        crate::host::http::handlers::messages::ContentBlockView,
        crate::host::http::handlers::messages::ToolResultContentView,
        crate::host::http::handlers::messages::CompactionMarker,
        crate::host::http::handlers::conversation::CompactRequestBody,
        crate::host::http::handlers::conversation::CompactResponse,
        crate::host::http::handlers::conversation::ContextResponse,
        crate::host::http::handlers::conversation::SessionTotals,
        crate::host::http::handlers::conversation::RewindRequestBody,
        crate::host::http::handlers::conversation::RewindResponse,
        crate::host::http::handlers::conversation::ImportResponse,
        crate::view::ScheduledJobView,
        crate::host::http::handlers::jobs::ScheduledJobsResponse,
        crate::view::GateView,
        crate::host::http::handlers::jobs::CreateJobRequest,
        crate::host::http::handlers::jobs::CreateGate,
        crate::host::http::handlers::jobs::BackgroundTaskView,
        crate::host::http::handlers::jobs::BackgroundTasksResponse,
        crate::view::SkillDetail,
        crate::host::http::handlers::stores::WriteSkillRequest,
        crate::view::MemoryDetail,
        crate::host::http::handlers::stores::MemoryListResponse,
        crate::host::http::handlers::stores::WriteMemoryRequest,
        crate::view::ToolView,
        crate::host::http::handlers::stores::ToolsResponse,
        crate::host::http::handlers::stores::InstructionsResponse,
        crate::view::ProfileView,
        crate::host::http::handlers::stores::ProfilesResponse,
        crate::host::http::handlers::info::InfoResponse,
        crate::view::SkillView,
        crate::host::http::handlers::info::McpServerStateView,
        crate::view::McpToolView,
        crate::view::McpToolsResponse,
        crate::host::http::handlers::info::McpReconnectResponse,
        crate::host::http::handlers::discovery::LiveResponse,
        crate::host::http::handlers::discovery::ReadyResponse,
    )),
    modifiers(&SecurityAddon),
    tags(
        (name = "sessions", description = "Session CRUD"),
        (name = "turn", description = "Turn lifecycle (submit / re-attach / cancel / mid-turn responses)"),
        (name = "conversation", description = "Compaction, rewind, context occupancy, export / import"),
        (name = "schedule", description = "Scheduled jobs"),
        (name = "tasks", description = "Background tasks"),
        (name = "skills", description = "Skill store CRUD"),
        (name = "memory", description = "Memory store CRUD"),
        (name = "discovery", description = "Server info, tools, instructions, profiles, MCP"),
        (name = "health", description = "Liveness / readiness probes"),
    )
)]
pub(crate) struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi
            .components
            .get_or_insert_with(utoipa::openapi::Components::default);
        components.add_security_scheme(
            "bearerAuth",
            SecurityScheme::Http(
                Http::builder()
                    .scheme(HttpAuthScheme::Bearer)
                    .description(Some(
                        "Bearer token configured in [[serve.tokens]]. Scopes: sessions:r, \
                         sessions:w, skills:r, skills:w, memory:r, memory:w, schedule:r, \
                         schedule:w, mcp:r, mcp:w.",
                    ))
                    .build(),
            ),
        );
    }
}

/// Wire the OpenAPI JSON endpoint and Swagger UI into the router. Both are public (no bearer
/// auth) so cross-language client tooling can hit them. `SwaggerUi` registers both
/// `/v1/docs/*` and `/v1/openapi.json` itself; no manual route definition is needed.
pub(crate) fn router() -> Router<ServerState> {
    Router::new().merge(SwaggerUi::new("/v1/docs").url("/v1/openapi.json", ApiDoc::openapi()))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every operation says who may call it and admits it can fail. A route is behind the bearer
    /// scheme with at least one scope named, or it is a health probe under `/v1/health`; and every
    /// route lists 500, because the problem-detail pipeline can produce one anywhere. The scopes a
    /// handler takes through `Scoped` are what the document has to say, or the document lies.
    #[test]
    fn every_operation_names_its_scopes_and_lists_500() {
        let document = ApiDoc::openapi();
        let mut problems = Vec::new();
        for (path, item) in &document.paths.paths {
            let operations = [
                ("get", &item.get),
                ("put", &item.put),
                ("post", &item.post),
                ("delete", &item.delete),
                ("patch", &item.patch),
            ];
            for (method, operation) in operations {
                let Some(operation) = operation else {
                    continue;
                };
                let label = format!("{method} {path}");
                // Serialized rather than read through the struct, whose fields are private: a
                // requirement renders as `{"bearerAuth": ["sessions:w"]}`.
                let security =
                    serde_json::to_value(&operation.security).expect("security serializes");
                let scopes: Vec<&serde_json::Value> = security
                    .as_array()
                    .into_iter()
                    .flatten()
                    .filter_map(|requirement| requirement.as_object())
                    .flat_map(|requirement| requirement.values())
                    .filter_map(|listed| listed.as_array())
                    .flatten()
                    .collect();
                if !path.starts_with("/v1/health") && scopes.is_empty() {
                    problems.push(format!("{label} names no scope"));
                }
                if !operation.responses.responses.contains_key("500") {
                    problems.push(format!("{label} does not list 500"));
                }
            }
        }
        assert!(problems.is_empty(), "{}", problems.join("\n"));
    }
}
